version: "3.8"
name: spark-cluster-docker
services:
  # docker run --rm -it --name spark bitnami/spark:latest spark-shell
  # docker run -d --name master --network spark-connect -p 8888:8080 -p 7077:7077 apache/spark /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
  # docker exec -it --user root spark-master bash
  # pip3 install pyspark
  spark-master:
    image: spark:3.5.1
    container_name: spark_master
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "-h",
        "spark-master",
      ]
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
      - SPARK_RPC_ENCRYPTION_ENABLED=false
      - SPARK_SSL_ENABLED=false
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port
    networks:
      - bridge

  # docker compose up --scale worker=4
  # docker run -d --name worker1 --network spark-connect -e SPARK_WORKER_MEMORY=1g -e SPARK_WORKER_CORE=2 apache/spark /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 
  spark-worker:
    image: spark:3.5.1
    container_name: spark_worker_1
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077",
      ]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      # - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_MEMORY=256m
    depends_on:
      - spark-master
    networks:
      - bridge

  # docker run --rm -p 8888:8888 -p 4040:4040 -v ./jupyter:/home/jupyter jupyter/pyspark-notebook:latest
  # from pyspark.sql import SparkSession
  # spark = SparkSession.builder \
  #  .master("spark://spark-master:7077") \
  #  .appName("Jupytertest") \
  #  .getOrCreate()
  jupyter:
    image: jupyter/pyspark-notebook:latest # PySpark 지원 이미지
    ports:
      - "8088:8888"
    environment:
      - SPARK_MASTER=spark://spark-master:7077 # 마스터 주소 설정
      - JUPYTER_ENABLE_LAB=yes # Enable JupyterLab interface
      - JUPYTER_TOKEN=1234 # 보안 토큰 (선택적)
    depends_on:
      - spark-master
    volumes:
      # Mount your local work directory into the container
      - "./Jupyter:/home/jovyan/work:rw"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
